### ISSUE TITLE
List/Grid Toggle

### ISSUE THREAD

**Issue by anuraagbaishya** [kartikarora/Transfer.sh#1]
A toggle can be added to change between a list and a grid to show files in the Transfer Activity

**Comment by kartikarora** [comment]
@anuraagbaishya Thanks for this, I'll have a look at it soon :)

**Comment by kartikarora** [comment]
@anuraagbaishya, I had set the no of columns for the grid view to be 2 in portrait and 3 in landscape, but it's showing only 2 in landscape when it the app is in grid mode. Could you please have a look at that an send a new PR fixing this?
