### ISSUE TITLE
change API server URL

### ISSUE THREAD

**Issue by jumpswitch** [kartikarora/Transfer.sh#11]
It would be nice if user could change URL to their own instance of transfer.sh web server.

**Comment by kartikarora** [comment]
That would actually be a nice addition. Do you have a URL for a custom instance where I can test it out? 

@mrizvic

**Comment by jumpswitch** [comment]
I just setup test instance for this testing purposes.
http://transfersh-dev.ts.si:8080/

**Comment by kartikarora** [comment]
I'm unable to open that page. @mrizvic 
It doesn't respond and ultimately the page timeouts

**Comment by jumpswitch** [comment]
IP was address changed. Try again. It should work now. I setup static IP this time.

**Comment by kartikarora** [comment]
Hey @mrizvic I've added the functionality, would you like to test it?
https://transfer.sh/4Knb4/transfer-debug.apk

**Comment by jumpswitch** [comment]
I downloaded it and allowed to install from unknown sources but after a few seconds of 'installing' it says 'App not installed'. How can I see the reason why not? Im on Android 6.0.1(Samsung S5)

**Comment by kartikarora** [comment]
Don't worry about it. It's on Play Store beta now https://play.google.com/apps/testing/me.kartikarora.transfersh

**Comment by jumpswitch** [comment]
Its installed now but it crashes shortly after running. I filled in report.

**Comment by jumpswitch** [comment]
I updated from play store beta and it works. My private server is on IPv6 only. Thank you :)
