### ISSUE TITLE
Improve file information view

### ISSUE THREAD

**Issue by kartikarora** [kartikarora/Transfer.sh#3]
The current file information alert dialog, which can be accessed by tapping on the info button of a file, is pretty bland. If anyone has a proposal for improvement, feel free to discuss here.

**Comment by dhruv2601** [comment]
Hi @kartikarora I have sent the PR for the above, please review.

**Comment by kartikarora** [comment]
@dhruv2601 Thanks for the PR. I'll have a look soon!

**Comment by kartikarora** [comment]
closing as a non issue
